* Encoding: UTF-8.
get file="\cc\misc2\extensions\r\stats_exrasch\tests\chart example data.sav".
dataset name data.

STATS EXRASCH MODEL=RSM ITEMS=Q6.1 Q6.2 Q6.3 Q6.4 Q6.5 REPS=1
/OPTIONS SUM0=YES SE=YES
/OUTPUT ITEMINFOPLOT=YES DESIGNMATRIX=NO THRESH=NO
ITEMPERSONPLOT=YES ETA=NO ICCPLOT=YES.


STATS EXRASCH MODEL=RSM ITEMS=Q6.1 Q6.2 Q6.3 Q6.4 Q6.5 REPS=1
/OPTIONS SUM0=YES SE=YES
/OUTPUT ITEMINFOPLOT=NO DESIGNMATRIX=NO THRESH=NO
ITEMPERSONPLOT=NO ETA=NO ICCPLOT=YES.


STATS EXRASCH MODEL=RSM  ITEMS=Q6.1 Q6.2 Q6.3 Q6.4 Q6.5  REPS=1
/OPTIONS SUM0=YES SE=YES
/OUTPUT ITEMINFOPLOT=NO DESIGNMATRIX=NO THRESH=NO 
ITEMPERSONPLOT=NO ETA=NO ICCPLOT=YES  ICCPLOTLEGENDPOS=LEFT.

STATS EXRASCH MODEL=RSM  ITEMS=Q6.1 Q6.2 Q6.3 Q6.4 Q6.5  REPS=1
/OPTIONS SUM0=YES SE=YES
/OUTPUT ITEMINFOPLOT=NO DESIGNMATRIX=NO THRESH=NO 
ITEMPERSONPLOT=NO ETA=NO ICCPLOT=YES ICCPLOTTYPE=separate ICCPLOTLEGENDPOS=RIGHT.
